.PHONY: clean All

All:
	@echo "----------Building project:[ 35_stack_demo - Debug ]----------"
	@cd "35_stack_demo" && "$(MAKE)" -f  "35_stack_demo.mk"
clean:
	@echo "----------Cleaning project:[ 35_stack_demo - Debug ]----------"
	@cd "35_stack_demo" && "$(MAKE)" -f  "35_stack_demo.mk" clean
